# Generated by Django 5.0.4 on 2024-05-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
